### ISSUE TITLE
Loto-ID manip?

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [zaksabeast/PokemonRNGGuides#211]
# Guide Details

## I want to (select one)

- [* ] Add a guide
- [ ] Modify an existing guide

## Games affected

- All Pokemon games that have a Loto-ID

## Type of RNG

Lottery RNG

## Language

English

## Notes

infinite master balls

**Comment by RichardPaulAstley** [comment]
That's not how the github and we work.
If you do this kind of PRs, it's for adding content, not suggesting content.

If you want these, you'll either : 
* Look around 
* Research in your own.

We're two to handle the site, and I'm working on the guides part, and I've to said that these aren't my priorities at all since you have some niche informations findable.
